name: build

on:
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [foo, teste]
    steps:
    - run: cat config.yml
      working-directory: "python/${{ matrix.package }}"
