name: build
on:
  pull_request:
    branches: [master]
    
jobs:

  packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"package\":[$(find . -name config.yml -exec dirname {} \; | sed "s|^\./||" | sed 's/.*/"&"/' | grep -v / | tr '\n' ',' | sed 's/.$//')]}"
      working-directory: "python"

  job2:
    needs: packages
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.packages.outputs.matrix)}}
      
    steps:
      - uses: actions/checkout@v2

      - name: Testing package ${{ matrix.package }}
        run: ls

      - name: Publishing package ${{ matrix.package }}
        run: cat python/${{ matrix.package }}/config.yml