name: build
on:
  pull_request:
    branches: [master]
    
jobs:

  packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"package\":[$(find . -name config.yml -exec dirname {} \; | sed "s|^\./||" | sed 's/.*/"&"/' | grep -v / | tr '\n' ',' | sed 's/.$//')]}"
      working-directory: "python"

  job2:
    needs: packages
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.packages.outputs.matrix)}}
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Test with Pytest
        if: hashFiles('/tests/test_**.py') != ''
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pytest tests/
        working-directory: "python/${{ matrix.package }}"
